executor: slurm
default-resources:
  - slurm_account="swc-ac"
  - slurm_partition="gpu"
  - mem_mb=64000
  - runtime="1d"
  - slurm_extra="--mail-type=BEGIN,END,FAIL --mail-user=s.kuroda@ucl.ac.uk"
restart-times: 1
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 5
keep-going: True
rerun-incomplete: True
printshellcmds: True
use-conda: True