import os

# Load input list from a file
with open(os.environ["INPUT_LIST"]) as f:
    input_files = [line.strip() for line in f if line.strip()]

def get_log_path(path):
    return f"{os.environ['LOG_DIR']}/{os.path.splitext(os.path.basename(path))[0]}.log"

# .avi files that need conversion
avi_input_files = [p for p in input_files if p.endswith(".avi")]

# .mp4 files that are already in the right format
mp4_input_files = [p for p in input_files if p.endswith(".mp4")]

# Mapping 
mp4_from_avi = [p.replace(".avi", ".mp4") for p in avi_input_files]
mp4_to_avi = dict(zip(mp4_from_avi, avi_input_files))
log_files = [get_log_path(p) for p in input_files]
all_mp4_files = mp4_from_avi + mp4_input_files
log_to_mp4 = dict(zip(log_files, all_mp4_files))

# Rules
rule all:
    input:
        all_mp4_files,
        log_files

rule convert_video:
    input:
        avi = lambda wildcards: mp4_to_avi.get(f"{wildcards.output}", "")
    output:
        mp4 =  "{output}"
    wildcard_constraints:
        output = ".*mp4"
    threads: 4
    shell:
        "ffmpeg -i {input.avi} -y -c:v libx264 -crf 20 -preset medium {output.mp4} -hide_banner -loglevel error"

rule extract_frames:
    input:
        mp4 = lambda wildcards: log_to_mp4.get(f"{wildcards.output}", "")
    output:
        log =  "{output}"
    wildcard_constraints:
        output = ".*log"
    params:
        dest = os.environ["DEST_CEPH"],
        PUPILSENSE_PATH = os.environ["PUPILSENSE_PATH"]
    threads: 4
    run:
        import os
        sys.path.append(params.PUPILSENSE_PATH)
        from pupilsense.extract_frames import main

        main(
            input_file_location = input.mp4,
            log = output.log,
            output = params.dest
        )